const personsData = [
  {
    fisrtname: "Billie",
    lastname: " Lyons",
    email: "billielyons@netropic.com",
    phone: "+1 (918) 539-3202",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },

  {
    fisrtname: "Manning",
    lastname: " Zamora",
    email: "manningzamora@netropic.com",
    phone: "+1 (899) 416-3320",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "formateur",
  },
  {
    fisrtname: "Lupe",
    lastname: " Keller",
    email: "lupekeller@netropic.com",
    phone: "+1 (893) 493-3176",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Jillian",
    lastname: " Fleming",
    email: "jillianfleming@netropic.com",
    phone: "+1 (896) 558-3580",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Maureen",
    lastname: " Padilla",
    email: "maureenpadilla@netropic.com",
    phone: "+1 (808) 442-3297",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Wolfe",
    lastname: " Sweet",
    email: "wolfesweet@netropic.com",
    phone: "+1 (968) 439-3482",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "formateur",
  },
  {
    fisrtname: "Frost",
    lastname: " Mendez",
    email: "frostmendez@netropic.com",
    phone: "+1 (829) 456-3326",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "formateur",
  },
  {
    fisrtname: "Rachel",
    lastname: " Moran",
    email: "rachelmoran@netropic.com",
    phone: "+1 (873) 547-3095",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "formateur",
  },
  {
    fisrtname: "Katrina",
    lastname: " Harper",
    email: "katrinaharper@netropic.com",
    phone: "+1 (811) 570-2696",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Pam",
    lastname: " Mcdonald",
    email: "pammcdonald@netropic.com",
    phone: "+1 (909) 513-2303",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Edwards",
    lastname: " Castaneda",
    email: "edwardscastaneda@netropic.com",
    phone: "+1 (971) 471-2146",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Hardin",
    lastname: " Horn",
    email: "hardinhorn@netropic.com",
    phone: "+1 (933) 473-3685",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "formateur",
  },
  {
    fisrtname: "Kaye",
    lastname: " Johnson",
    email: "kayejohnson@netropic.com",
    phone: "+1 (951) 408-2671",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Della",
    lastname: " Noel",
    email: "dellanoel@netropic.com",
    phone: "+1 (918) 499-3598",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Kristina",
    lastname: " Simpson",
    email: "kristinasimpson@netropic.com",
    phone: "+1 (904) 483-2836",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Conner",
    lastname: " Harris",
    email: "connerharris@netropic.com",
    phone: "+1 (876) 506-3091",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Twila",
    lastname: " Berry",
    email: "twilaberry@netropic.com",
    phone: "+1 (971) 546-3447",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Earline",
    lastname: " Walters",
    email: "earlinewalters@netropic.com",
    phone: "+1 (847) 458-2181",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "formateur",
  },
  {
    fisrtname: "Jeannie",
    lastname: " Macias",
    email: "jeanniemacias@netropic.com",
    phone: "+1 (827) 452-3401",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Tanya",
    lastname: " Watts",
    email: "tanyawatts@netropic.com",
    phone: "+1 (858) 458-3923",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Norris",
    lastname: " Brennan",
    email: "norrisbrennan@netropic.com",
    phone: "+1 (985) 486-3244",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Potter",
    lastname: " Bennett",
    email: "potterbennett@netropic.com",
    phone: "+1 (931) 503-2477",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Avila",
    lastname: " Cruz",
    email: "avilacruz@netropic.com",
    phone: "+1 (803) 546-2818",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "formateur",
  },
  {
    fisrtname: "Yolanda",
    lastname: " Carver",
    email: "yolandacarver@netropic.com",
    phone: "+1 (891) 548-2269",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Berta",
    lastname: " Valencia",
    email: "bertavalencia@netropic.com",
    phone: "+1 (849) 536-2150",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Hattie",
    lastname: " Stephens",
    email: "hattiestephens@netropic.com",
    phone: "+1 (944) 432-3333",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Minerva",
    lastname: " Kennedy",
    email: "minervakennedy@netropic.com",
    phone: "+1 (808) 541-3172",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Andrews",
    lastname: " Townsend",
    email: "andrewstownsend@netropic.com",
    phone: "+1 (806) 464-3300",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Ashlee",
    lastname: " Winters",
    email: "ashleewinters@netropic.com",
    phone: "+1 (913) 528-2130",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Rae",
    lastname: " Baldwin",
    email: "raebaldwin@netropic.com",
    phone: "+1 (900) 592-3689",
    picture: "https://www.fillmurray.com/180/180",
    isActive: true,
    test: "developer",
  },
  {
    fisrtname: "Casandra",
    lastname: " Evans",
    email: "casandraevans@netropic.com",
    phone: "+1 (922) 581-3892",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Nellie",
    lastname: " Huff",
    email: "nelliehuff@netropic.com",
    phone: "+1 (939) 520-3209",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
  {
    fisrtname: "Castaneda",
    lastname: " Fry",
    email: "castanedafry@netropic.com",
    phone: "+1 (869) 520-3829",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "formateur",
  },
  {
    fisrtname: "Laverne",
    lastname: " Schneider",
    email: "laverneschneider@netropic.com",
    phone: "+1 (862) 456-2583",
    picture: "https://www.fillmurray.com/180/180",
    isActive: false,
    test: "developer",
  },
];
function personTemplate(person) {
  return `
  <div class="people">
    <img class = "person-photo" src="${person.picture}">
    <h2 class="person-firstName">${person.fisrtname}${person.lastname}<span class="test">(${person.test})</span></h2>
    `;
}

document.getElementById("app").innerHTML = `<h4 class="app-title">Name1(${
  personsData.length
} results) </h4>
${personsData.map(personTemplate).join("")}
<p class="footer"> These ${
  personsData.length
} person was added recently.Check back soon for updates`;
